version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server
    user: root
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=TestP4ssword?
      - ACCEPT_EULA=Y
    volumes:
      - db:/var/opt/mssql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    image: greedygrinner1/syp024b06frontend:1.1
    ports:
      - "4200:80"

  backend:
    image: greedygrinner1/syp024b06backend:1.2
    ports:
      - "7000:7000"
    depends_on:
      - db
    links:
      - db

volumes:
  db:
    driver: local